#!/usr/bin/env python3
"""Generate deterministic release SBOM and human-readable provenance metadata."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import tomllib
import uuid
from pathlib import Path

REPOSITORY = "Pavithran-R-A/clipgauge"
FORBIDDEN_SOURCE_COMMIT = "c4f4a1f5cae4cdfc7b98c719387946896062e7fb"


def run_git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=root, text=True).strip()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def load_toml(path: Path) -> dict:
    return tomllib.loads(path.read_text())


def version_from_tag(tag: str) -> str:
    match = re.fullmatch(r"v(\d+\.\d+\.\d+)", tag)
    if not match:
        raise SystemExit(f"release tag must have vMAJOR.MINOR.PATCH form, found {tag!r}")
    return match.group(1)


def component(*, name: str, version: str, purl: str, scope: str | None = None) -> dict:
    value = {
        "type": "application" if scope == "first-party" else "library",
        "bom-ref": purl,
        "name": name,
        "version": version,
        "purl": purl,
    }
    if scope:
        value["scope"] = scope
    return value


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", required=True, help="Release tag, for example v0.1.1")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--checksum-manifest", type=Path)
    parser.add_argument("--workflow-run")
    parser.add_argument("--attestation-status", default="not generated by this script")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    version = version_from_tag(args.tag)
    package_json = load_json(root / "app/package.json")
    tauri = load_json(root / "app/src-tauri/tauri.conf.json")
    cargo = load_toml(root / "app/src-tauri/Cargo.toml")
    pyproject = load_toml(root / "pipeline/pyproject.toml")
    pipeline_init = (root / "pipeline/clipgauge_pipeline/__init__.py").read_text()
    init_match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']\s*$', pipeline_init, re.MULTILINE)
    if init_match is None:
        raise SystemExit("pipeline package version constant is missing")
    authoritative = {
        "frontend": package_json.get("version"),
        "tauri": tauri.get("version"),
        "rust": cargo.get("package", {}).get("version"),
        "python": pyproject.get("project", {}).get("version"),
        "pipeline": init_match.group(1),
    }
    mismatches = {name: found for name, found in authoritative.items() if found != version}
    if mismatches:
        raise SystemExit(f"authoritative versions do not match {version}: {mismatches}")

    try:
        source_commit = run_git(root, "rev-parse", f"{args.tag}^{{}}")
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"cannot resolve peeled source commit for {args.tag}") from exc
    if not re.fullmatch(r"[0-9a-f]{40}", source_commit):
        raise SystemExit(f"resolved source commit is not a full SHA-1: {source_commit!r}")
    if source_commit == FORBIDDEN_SOURCE_COMMIT:
        raise SystemExit("resolved source commit is the forbidden stale v0.1.0 tag object")

    cargo_lock = load_toml(root / "app/src-tauri/Cargo.lock")
    uv_lock = load_toml(root / "pipeline/uv.lock")
    cargo_dependencies = [p for p in cargo_lock.get("package", []) if p.get("name") != "clipgauge-app"]
    python_dependencies = [p for p in uv_lock.get("package", []) if p.get("name") != "clipgauge-pipeline"]
    components = [
        component(name="ClipGauge desktop application", version=version, purl=f"pkg:generic/clipgauge-app@{version}", scope="first-party"),
        component(name="ClipGauge Python pipeline", version=version, purl=f"pkg:generic/clipgauge-pipeline@{version}", scope="first-party"),
    ]
    components.extend(
        component(name=p["name"], version=p["version"], purl=f"pkg:cargo/{p['name']}@{p['version']}")
        for p in cargo_dependencies
    )
    components.extend(
        component(name=p["name"], version=p["version"], purl=f"pkg:pypi/{p['name']}@{p['version']}")
        for p in python_dependencies
    )
    refs = [p["bom-ref"] for p in components]
    if len(refs) != len(set(refs)):
        raise SystemExit("duplicate BOM references detected during generation")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    sbom = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "serialNumber": f"urn:uuid:{uuid.uuid5(uuid.NAMESPACE_URL, f'{REPOSITORY}@{args.tag}#{source_commit}')}",
        "version": 1,
        "metadata": {
            "component": component(name="ClipGauge", version=version, purl=f"pkg:generic/clipgauge@{version}", scope="first-party"),
            "properties": [
                {"name": "source.repository", "value": REPOSITORY},
                {"name": "source.tag", "value": args.tag},
                {"name": "source.commit", "value": source_commit},
                {"name": "sbom.scope", "value": "Rust and Python lockfile dependencies plus ClipGauge first-party package metadata; optional model weights, downloaded runtimes, user data, credentials, and hardware state are excluded."},
            ],
        },
        "components": components,
    }
    sbom_path = args.output_dir / "SBOM.cyclonedx.json"
    sbom_path.write_text(json.dumps(sbom, indent=2) + "\n")

    checksum_lines: list[str] = []
    if args.checksum_manifest and args.checksum_manifest.exists():
        checksum_lines = [line.strip() for line in args.checksum_manifest.read_text().splitlines() if line.strip()]
    checksum_block = "\n".join(f"- `{line}`" for line in checksum_lines) or "- Checksums are generated by the publication job from the exact transferred release assets."
    workflow = args.workflow_run or "not supplied"
    provenance = f"""# ClipGauge v{version} Release Provenance

This human-readable record accompanies the v{version} release. It is metadata, not a cryptographic signature, platform code signature, notarization record, or GitHub artifact attestation.

| Field | Value |
|---|---|
| Repository | `https://github.com/{REPOSITORY}` |
| Release tag | `{args.tag}` |
| Peeled source commit | `{source_commit}` |
| Workflow run | `{workflow}` |
| Attestation status | {args.attestation_status} |
| Platform signing | Unsigned unless a release asset explicitly states otherwise |
| SBOM scope | Rust and Python lockfile dependencies plus ClipGauge first-party package metadata; optional model weights, downloaded runtimes, user data, credentials, and hardware state are excluded |

## Checksums

The following lines were supplied from the publication job's checksum manifest:

{checksum_block}

The existing historical v0.1.0 tag and release are not modified by this release. Upstream attribution, the AGPL-3.0-or-later license, and the audited upstream baseline remain preserved.
"""
    (args.output_dir / "RELEASE_PROVENANCE.md").write_text(provenance)
    print(f"generated {sbom_path}")
    print(f"generated {args.output_dir / 'RELEASE_PROVENANCE.md'}")
    print(f"source_commit={source_commit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
